[project]
name = "shaderbang"
version = "0.1.0"
dependencies = [
    "libevdev",
]
requires-python = ">=3.10"
authors = [
    { name = "Antonin Stefanutti" },
]
description = "A Python toolkit for OpenGL rendering with EGL/DRM/KMS"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
GitHub = "https://github.com/astefanutti/shaderbang"

[project.scripts]
shadertoy = "shaderbang.shadertoy.__main__:main"

[build-system]
requires = ["setuptools>=75.3.2", "build", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp313-manylinux*"
archs = "x86_64 aarch64 armv7l"
before-all = """if command -v yum > /dev/null; then yum install -y libdrm-devel mesa-libgbm-devel mesa-libEGL-devel mesa-libGLES-devel; elif command -v apt-get > /dev/null; then apt-get update && apt-get install -y libdrm-dev libgbm-dev libegl-dev libgles2-mesa-dev; fi"""
